server:
  port: 9992
  context-path: /

spring:
  thymeleaf:
    prefix: classpath:/templates/
  ## 数据源配置
  datasource:
    url: jdbc:mysql://rm-wz9cx0j1qeen1opba8o.mysql.rds.aliyuncs.com:3306/macau?useUnicode=true&characterEncoding=utf8
    password: AoMi@2020
    username: aomi
    driver-class-name: com.mysql.jdbc.Driver
## Mybatis配置
mybatis:
  type-aliases-package: springboot.demo.domain
  mapper-locations: classpath:mapper/*.xml
logging:
  config: classpath:log4j2.xml