spring:
  ## 数据源配置
  datasource:
    url: jdbc:mysql://rm-wz9cx0j1qeen1opba8o.mysql.rds.aliyuncs.com:3306/macau?useUnicode=true&characterEncoding=utf8
    password: AoMi@2020
    username: aomi
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    host: r-wz925fb8fbfcd7c4pd.redis.rds.aliyuncs.com
    port: 6379
    password: TestAomi2020!
#
#  redis:
#    host: localhost
#    port: 6379

#    cache:
#      type: redis
#
#      # These properties are custom
#      multilevel:
#        # Redis properties
#        time-to-live: 1h
#        use-key-prefix: false
#        key-prefix: ""
#        topic: "cache:multilevel:topic"
#        # Local Caffeine cache properties
#        local:
#          max-size: 2000
#          expiry-jitter: 50
#        # Resilience4j Circuit Breaker properties for Redis
#        circuit-breaker:
#          failure-rate-threshold: 25
#          slow-call-rate-threshold: 25
#          slow-call-duration-threshold: 250ms
#          sliding-window-type: count_based
#          permitted-number-of-calls-in-half-open-state: 20
#          max-wait-duration-in-half-open-state: 5s
#          sliding-window-size: 40
#          minimum-number-of-calls: 10
#          wait-duration-in-open-state: 2500ms