server:
  port: 8080
  error:
    whitelabel:
      enabled: false
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

spring:
  profiles:
    active: dev
  thymeleaf:
    prefix: classpath:/templates/

## Mybatis配置
mybatis:
  type-aliases-package: springboot.demo.domain
  mapper-locations: classpath:mapper/*.xml

logging:
  config: classpath:log4j2.xml
  level:
    springboot.demo: debug

logbook:
  include: /**
  format:
    style: http
  write:
    level: info