spring:
  ## 数据源配置
  datasource:
    url: jdbc:mysql://rm-wz9cx0j1qeen1opba8o.mysql.rds.aliyuncs.com:3306/macau?useUnicode=true&characterEncoding=utf8
    password: AoMi@2020
    username: aomi
    driver-class-name: com.mysql.jdbc.Driver
