@startuml
top to bottom direction

!include <C4/C4_Container>
!include <C4/C4_Context>

LAYOUT_WITH_LEGEND()
title 票务系统 - Context

Person(customer, "用户")
System(ticketing, "票务系统")
Person(ticketSeller, "售票员")

customer -> ticketing : Requests tickets
ticketSeller -> ticketing : Sells tickets
@enduml